version: '3'

services:
    report-service:
        restart: always
        build: report-service
        links:
          - test-service
        ports:
          - "5601:5601"
          - "9200:9200"
          - "5044:5044"

#    test-service:
#        restart: always
#        build: docker-distribution-test
#        environment:
#          - "ACTIVE_ENVIRONMENT=$ENVIRONMENT"
#          - "TEST_SUITE_EXECUTION=$SUITE"
#        volumes:
#          - maven-repo:/root/.m2

volumes:
    maven-repo: